documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

devops:
- changed-files:
  - any-glob-to-any-file:
    - .github/*
    - .gitignore

mission:
- changed-files:
  - any-glob-to-any-file:
    - 'Missions/**/*'
    - 'worlds/**/*'