SCR_MissionHeader {
 World "{EA743DA57E61E266}worlds/FloridaMan/worlds/BattleForSkalistyIslandP1/BattleForSkalistyIslandP1.ent"
 m_sName "TVT (49-94) Battle for Skalisty Island"
 m_sAuthor "FloridaMan"
 m_sDescription "U.S. MARSOC and Russian SSO race to secure a disgraced FIA general hiding on Skalisty Island."
 m_sGameMode "TVT"
 m_iPlayerCount 94
 m_iMapMarkerLimitPerPlayer 67
}