SCR_MissionHeader {
 World "{C33E0F6DC44C8D2B}worlds/Delfer/Topdown/GM_Zarichne.ent"
 m_sName "COTVT (40-68) Topdown"
 m_sAuthor "Delfer"
 m_sDescription "Russian Company fights through an International Legion Platoon's defense in a trench system."
 m_iPlayerCount 68
}