SCR_MissionHeader {
 World "{1410AE5642D6E8FF}worlds/TheLocalPub/SandySAM/SandySAM.ent"
 m_sName "COTVT (25-65) SandySAM"
 m_sAuthor "TheLocalPub"
 m_sDescription "UK special forces move in the early hours of the morning to destroy a known Iraqi anti-aircraft site on the outskirts of the city, shaping the battlespace for follow-on air operations."
 m_sDetails "UK special forces move in the early hours of the morning to destroy a known Iraqi anti-aircraft site on the outskirts of the city, shaping the battlespace for follow-on air operations."
 m_iPlayerCount 65
}