SCR_ScenarioFrameworkActionQRFDispacher_modified {
 m_sQRFLayerName "QRFSpawnpointsLayer"
 m_iNumberOfAvailableQRFWaves 3
 m_fThreatLevelEscalation 1.5
 m_fQRFSpawnDelay 15
 m_fQRFNextWaveDelay 120
 m_aQRFMaxDistanceConfig {
  SCR_QRFTypeMaxDistance "{694621DC887C757A}" {
   m_iMaxSpawnDistance 250
  }
  SCR_QRFTypeMaxDistance "{694621DC887C7579}" {
   m_eGroupType MOUNTED_INFANTRY
   m_iMaxSpawnDistance 500
  }
  SCR_QRFTypeMaxDistance "{694621DC887C7578}" {
   m_eGroupType VEHICLE
   m_iMaxSpawnDistance 500
  }
  SCR_QRFTypeMaxDistance "{694621DC887C7577}" {
   m_eGroupType AIR
   m_iMaxSpawnDistance 2000
  }
 }
 m_aWPConfig {
  SCR_QRFWaypointConfig "{694621DC887C748D}" {
   m_sWPToSpawn "{2602CAB8AB74FBBF}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_GetOut.et"
   m_eGroupType MOUNTED_INFANTRY
   m_iDistanceOffsetToTargetLocation 150
  }
  SCR_QRFWaypointConfig "{694621DC887C748C}" {
   m_sWPToSpawn "{FFF9518F73279473}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_Move.et"
   m_eGroupType INFANTRY
   m_iDistanceOffsetToTargetLocation 150
  }
  SCR_QRFWaypointConfig "{694621DC887C748B}" {
   m_sWPToSpawn "{EE9A99488B40628B}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_SearchAndDestroy.et"
  }
  SCR_QRFWaypointConfig "{694621DC887C748A}" {
   m_sWPToSpawn "{D9C14ECEC9772CC6}PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_Defend.et"
   m_eGroupType INFANTRY
  }
 }
 m_sQRFRequestedSoundEventName "SOUND_REQUEST_QRF_USSR"
 m_sQRFSentSoundEventName "SOUND_CONFIRM_QRF_USSR"
 m_sSoundProjectFile "{A65355A96C153C12}Sounds/RadioProtocol/RadioProtocol_ScenarioFramework_QRF.acp"
}