SCR_MissionHeader {
 World "{111B7B7F80232053}worlds/Jub/OperationArrowheadMulladostPass/OperationArrowheadMulladostPass.ent"
 m_sName "COOP (26-47) Operation Arrowhead Mulladost Pass"
 m_sAuthor "jubxxxjub"
 m_sDescription "A US Army SBCT Rifle platoon, and MGS conduct an advance to contact to Mulladost, to clear a route and sweep the village. They are supported by an AH-64."
 m_sIcon "{C99FD0EFFCF7E002}Assets/Structures/Signs/Large/Data/1024x1024_Takistan.edds"
 m_sLoadingScreen "{CD88E8B5D0BE8933}Assets/Structures/Signs/Large/Data/1024x1024_Tabacco.edds"
 m_sPreviewImage "{1DE23426DE742AEB}Assets/Structures/Signs/Large/Data/1024x1024_Zargabad.edds"
 m_sGameMode "COOP"
 m_iPlayerCount 47
 m_iMapMarkerLimitPerPlayer 20
 m_GC_Metadata GC_MissionMetadata "{6A7A28674E455299}" {
  m_FriendlyForce GC_ForceDefinition "{6A7A28674FAC2249}" {
   m_sFactionKey "US"
   m_eType MOTORIZED
  }
  m_OpposingForce GC_ForceDefinition "{6A7A286747F7A37D}" {
   m_sFactionKey "GC_TKA"
   m_eType COMBINED
  }
  m_eEra ERA_2000s
  m_eSpecialAssets {
   ATK_HELIS
  }
 }
}