SCR_MissionHeader {
 World "{DB70A9D2267AF98A}worlds/Reapzr/Desert Spear/Desert Spear.ent"
 m_sName "COTVT (60-100)"
 m_sAuthor "Reapzr"
 m_sDescription "Coalition special forces conduct a deliberate extraction of UK infantry from insurgent-controlled Al-Hadra compound."
}